// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAURNVpj0XiJaCSvNN-nTnSiouUFuE1E9k',
    appId: '1:982165859272:web:0a88cdc4bc73410d8beefd',
    messagingSenderId: '982165859272',
    projectId: 'omnibooking-58f9a',
    authDomain: 'omnibooking-58f9a.firebaseapp.com',
    storageBucket: 'omnibooking-58f9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAURNVpj0XiJaCSvNN-nTnSiouUFuE1E9k',
    appId: '1:982165859272:android:0a88cdc4bc73410d8beefd',
    messagingSenderId: '982165859272',
    projectId: 'omnibooking-58f9a',
    storageBucket: 'omnibooking-58f9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURNVpj0XiJaCSvNN-nTnSiouUFuE1E9k',
    appId: '1:982165859272:ios:0a88cdc4bc73410d8beefd',
    messagingSenderId: '982165859272',
    projectId: 'omnibooking-58f9a',
    storageBucket: 'omnibooking-58f9a.firebasestorage.app',
    iosBundleId: 'com.example.omnibooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURNVpj0XiJaCSvNN-nTnSiouUFuE1E9k',
    appId: '1:982165859272:macos:0a88cdc4bc73410d8beefd',
    messagingSenderId: '982165859272',
    projectId: 'omnibooking-58f9a',
    storageBucket: 'omnibooking-58f9a.firebasestorage.app',
    iosBundleId: 'com.example.omnibooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAURNVpj0XiJaCSvNN-nTnSiouUFuE1E9k',
    appId: '1:982165859272:windows:0a88cdc4bc73410d8beefd',
    messagingSenderId: '982165859272',
    projectId: 'omnibooking-58f9a',
    storageBucket: 'omnibooking-58f9a.firebasestorage.app',
  );
}